### ISSUE TITLE
No LICENSE.md

### ISSUE THREAD

**Issue by m-kostrzewa** [jan-warchol/pan-deser#6]
Hi,

could you provide a license file? I want to fork this repo but don't know if I can.

**Comment by jan-warchol** [comment]
Hi,

this turned out to be surprisingly non-trivial, for two reasons:
- I intended to include some 3-rd party recipes that I tested and proved to be good, and I'm not sure how to handle licensing correctly
- for my own work, I will use creative commons, but I haven't decided which variant: CC-BY or CC-BY-NC. Do you think a license with non-commercial clause would be perceived as overly restrictive?
